import q11
import sys
from PyQt5 import QtCore, QtGui, QtWidgets,QtSql
import q11
import pymssql
from PyQt5.QtSql import QSqlQuery,QSqlDatabase,QSqlTableModel,QSqlRelation,QSqlRelationalDelegate, QSqlRelationalTableModel
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtCore import *
from PyQt5.QtCore import Qt

class main_function(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 800)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 80, 1191, 661))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("background-color: rgb(255, 255, 255);rr")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(36, 32))
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.bt1 = QtWidgets.QPushButton(self.tab)
        self.bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt1.setFont(font)
        self.bt1.setObjectName("bt1")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.bt1)
        self.bt2 = QtWidgets.QPushButton(self.tab)
        self.bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt2.setFont(font)
        self.bt2.setObjectName("bt2")
        self.bt3 = QtWidgets.QPushButton(self.tab)
        self.bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt3.setFont(font)
        self.bt3.setObjectName("bt3")
        self.bt4 = QtWidgets.QPushButton(self.tab)
        self.bt4.setGeometry(QtCore.QRect(20, 220, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt4.setFont(font)
        self.bt4.setObjectName("bt4")
        self.bt5 = QtWidgets.QPushButton(self.tab)
        self.bt5.setGeometry(QtCore.QRect(20, 270, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt5.setFont(font)
        self.bt5.setObjectName("bt5")
        self.bt6 = QtWidgets.QPushButton(self.tab)
        self.bt6.setGeometry(QtCore.QRect(60, 440, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.bt6.setFont(font)
        self.bt6.setObjectName("bt6")
        self.buttonGroup.addButton(self.bt6)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(20, 370, 101, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.id = QtWidgets.QLineEdit(self.tab)
        self.id.setGeometry(QtCore.QRect(20, 400, 131, 20))
        self.id.setObjectName("id")
        self.table_view = QtWidgets.QTableView(self.tab)
        self.table_view.setGeometry(QtCore.QRect(175, 11, 811, 601))
        self.table_view.setStyleSheet("")
        self.table_view.setObjectName("table_view")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.s_bt1 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt1.setFont(font)
        self.s_bt1.setObjectName("s_bt1")
        self.s_bt2 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt2.setFont(font)
        self.s_bt2.setObjectName("s_bt2")
        self.s_bt3 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt3.setFont(font)
        self.s_bt3.setObjectName("s_bt3")
        self.s_bt4 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt4.setGeometry(QtCore.QRect(20, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt4.setFont(font)
        self.s_bt4.setObjectName("s_bt4")
        self.s_bt5 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt5.setGeometry(QtCore.QRect(20, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt5.setFont(font)
        self.s_bt5.setObjectName("s_bt5")
        self.s_id = QtWidgets.QLineEdit(self.tab_2)
        self.s_id.setGeometry(QtCore.QRect(20, 380, 91, 20))
        self.s_id.setObjectName("s_id")
        self.s_bt6 = QtWidgets.QPushButton(self.tab_2)
        self.s_bt6.setGeometry(QtCore.QRect(110, 410, 51, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.s_bt6.setFont(font)
        self.s_bt6.setObjectName("s_bt6")
        self.table_view2 = QtWidgets.QTableView(self.tab_2)
        self.table_view2.setGeometry(QtCore.QRect(170, 10, 1001, 601))
        self.table_view2.setObjectName("table_view2")
        self.comboBox = QtWidgets.QComboBox(self.tab_2)
        self.comboBox.setGeometry(QtCore.QRect(20, 340, 91, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.sum1 = QtWidgets.QLineEdit(self.tab_2)
        self.sum1.setGeometry(QtCore.QRect(20, 410, 51, 31))
        self.sum1.setObjectName("sum1")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.t_bt1 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt1.setFont(font)
        self.t_bt1.setObjectName("t_bt1")
        self.t_bt2 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt2.setFont(font)
        self.t_bt2.setObjectName("t_bt2")
        self.t_bt3 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt3.setFont(font)
        self.t_bt3.setObjectName("t_bt3")
        self.t_bt4 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt4.setGeometry(QtCore.QRect(20, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt4.setFont(font)
        self.t_bt4.setObjectName("t_bt4")
        self.t_bt5 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt5.setGeometry(QtCore.QRect(20, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt5.setFont(font)
        self.t_bt5.setObjectName("t_bt5")
        self.t_bt6 = QtWidgets.QPushButton(self.tab_3)
        self.t_bt6.setGeometry(QtCore.QRect(110, 420, 51, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_bt6.setFont(font)
        self.t_bt6.setObjectName("t_bt6")
        self.t_id = QtWidgets.QLineEdit(self.tab_3)
        self.t_id.setGeometry(QtCore.QRect(20, 380, 91, 20))
        self.t_id.setObjectName("t_id")
        self.table_view3 = QtWidgets.QTableView(self.tab_3)
        self.table_view3.setGeometry(QtCore.QRect(170, 10, 1001, 601))
        self.table_view3.setObjectName("table_view3")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 350, 91, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.sum2 = QtWidgets.QLineEdit(self.tab_3)
        self.sum2.setGeometry(QtCore.QRect(20, 420, 51, 31))
        self.sum2.setObjectName("sum2")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.d_bt2 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt2.setFont(font)
        self.d_bt2.setObjectName("d_bt2")
        self.d_bt3 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt3.setFont(font)
        self.d_bt3.setObjectName("d_bt3")
        self.d_id = QtWidgets.QLineEdit(self.tab_4)
        self.d_id.setGeometry(QtCore.QRect(20, 380, 131, 20))
        self.d_id.setObjectName("d_id")
        self.d_bt1 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt1.setFont(font)
        self.d_bt1.setObjectName("d_bt1")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(20, 350, 101, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.d_bt4 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt4.setGeometry(QtCore.QRect(20, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt4.setFont(font)
        self.d_bt4.setObjectName("d_bt4")
        self.d_bt5 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt5.setGeometry(QtCore.QRect(20, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt5.setFont(font)
        self.d_bt5.setObjectName("d_bt5")
        self.d_bt6 = QtWidgets.QPushButton(self.tab_4)
        self.d_bt6.setGeometry(QtCore.QRect(60, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.d_bt6.setFont(font)
        self.d_bt6.setObjectName("d_bt6")
        self.table_view4 = QtWidgets.QTableView(self.tab_4)
        self.table_view4.setGeometry(QtCore.QRect(170, 10, 1001, 601))
        self.table_view4.setObjectName("table_view4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.c_bt2 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt2.setFont(font)
        self.c_bt2.setObjectName("c_bt2")
        self.c_bt3 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt3.setFont(font)
        self.c_bt3.setObjectName("c_bt3")
        self.c_id = QtWidgets.QLineEdit(self.tab_5)
        self.c_id.setGeometry(QtCore.QRect(20, 380, 131, 20))
        self.c_id.setObjectName("c_id")
        self.c_bt1 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt1.setFont(font)
        self.c_bt1.setObjectName("c_bt1")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(20, 350, 101, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(13)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.c_bt4 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt4.setGeometry(QtCore.QRect(20, 230, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt4.setFont(font)
        self.c_bt4.setObjectName("c_bt4")
        self.c_bt5 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt5.setGeometry(QtCore.QRect(20, 290, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt5.setFont(font)
        self.c_bt5.setObjectName("c_bt5")
        self.c_bt6 = QtWidgets.QPushButton(self.tab_5)
        self.c_bt6.setGeometry(QtCore.QRect(60, 420, 91, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.c_bt6.setFont(font)
        self.c_bt6.setObjectName("c_bt6")
        self.table_view5 = QtWidgets.QTableView(self.tab_5)
        self.table_view5.setGeometry(QtCore.QRect(170, 10, 1001, 601))
        self.table_view5.setObjectName("table_view5")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.x_id1 = QtWidgets.QLineEdit(self.tab_6)
        self.x_id1.setGeometry(QtCore.QRect(20, 340, 131, 20))
        self.x_id1.setObjectName("x_id1")
        self.x_bt2 = QtWidgets.QPushButton(self.tab_6)
        self.x_bt2.setGeometry(QtCore.QRect(20, 110, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_bt2.setFont(font)
        self.x_bt2.setObjectName("x_bt2")
        self.x_bt1 = QtWidgets.QPushButton(self.tab_6)
        self.x_bt1.setGeometry(QtCore.QRect(20, 50, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_bt1.setFont(font)
        self.x_bt1.setObjectName("x_bt1")
        self.x_bt4 = QtWidgets.QPushButton(self.tab_6)
        self.x_bt4.setGeometry(QtCore.QRect(80, 380, 71, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_bt4.setFont(font)
        self.x_bt4.setObjectName("x_bt4")
        self.x_bt3 = QtWidgets.QPushButton(self.tab_6)
        self.x_bt3.setGeometry(QtCore.QRect(20, 170, 131, 31))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.x_bt3.setFont(font)
        self.x_bt3.setObjectName("x_bt3")
        self.table_view6 = QtWidgets.QTableView(self.tab_6)
        self.table_view6.setGeometry(QtCore.QRect(170, 10, 1001, 601))
        self.table_view6.setObjectName("table_view6")
        self.sum3 = QtWidgets.QLineEdit(self.tab_6)
        self.sum3.setGeometry(QtCore.QRect(20, 380, 51, 31))
        self.sum3.setObjectName("sum3")
        self.tabWidget.addTab(self.tab_6, "")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 300, 111, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.tabWidget.addTab(self.tab_6, "")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 0, 81, 81))
        self.label_2.setStyleSheet("border-image: url(:/image/图片/t16.jpg);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(130, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 50, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 3, 3);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(320, 20, 131, 31))
        font = QtGui.QFont()
        font.setFamily("华文行楷")
        font.setPointSize(19)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("border-image: url(:/image/图片/t6.jpg);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 5, 711, 71))
        self.label_6.setStyleSheet("border-image: url(:/image/图片/t6.jpg);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "学生选课系统"))
        self.bt1.setText(_translate("MainWindow", "浏览账号"))
        self.bt2.setText(_translate("MainWindow", "添加账号"))
        self.bt3.setText(_translate("MainWindow", "删除账号"))
        self.bt4.setText(_translate("MainWindow", "更改信息"))
        self.bt5.setText(_translate("MainWindow", "撤销更改"))
        self.bt6.setText(_translate("MainWindow", "查询账号"))
        self.label.setText(_translate("MainWindow", "输入账号："))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "账号管理"))
        self.s_bt1.setText(_translate("MainWindow", "浏览学生"))
        self.s_bt2.setText(_translate("MainWindow", "添加学生"))
        self.s_bt3.setText(_translate("MainWindow", "删除学生"))
        self.s_bt4.setText(_translate("MainWindow", "更改信息"))
        self.s_bt5.setText(_translate("MainWindow", "撤销更改"))
        self.s_bt6.setText(_translate("MainWindow", "查询"))
        self.comboBox.setItemText(1, _translate("MainWindow", "学号"))
        self.comboBox.setItemText(2, _translate("MainWindow", "姓名"))
        self.comboBox.setItemText(3, _translate("MainWindow", "所属学院"))
        self.comboBox.setItemText(4, _translate("MainWindow", "性别"))
        self.sum1.setPlaceholderText(_translate("MainWindow", "总数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "学生管理"))
        self.t_bt1.setText(_translate("MainWindow", "浏览教师"))
        self.t_bt2.setText(_translate("MainWindow", "添加教师"))
        self.t_bt3.setText(_translate("MainWindow", "删除教师"))
        self.t_bt4.setText(_translate("MainWindow", "更改信息"))
        self.t_bt5.setText(_translate("MainWindow", "撤销更改"))
        self.t_bt6.setText(_translate("MainWindow", "查询"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "教工号"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "姓名"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "性别"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "所教课程"))
        self.sum2.setPlaceholderText(_translate("MainWindow", "总数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "教师管理"))
        self.d_bt2.setText(_translate("MainWindow", "添加院系"))
        self.d_bt3.setText(_translate("MainWindow", "删除院系"))
        self.d_bt1.setText(_translate("MainWindow", "浏览院系"))
        self.label_12.setText(_translate("MainWindow", "输入院系号："))
        self.d_bt4.setText(_translate("MainWindow", "更改信息"))
        self.d_bt5.setText(_translate("MainWindow", "撤销更改"))
        self.d_bt6.setText(_translate("MainWindow", "查询院系"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "院系管理"))
        self.c_bt2.setText(_translate("MainWindow", "添加课程"))
        self.c_bt3.setText(_translate("MainWindow", "删除课程"))
        self.c_bt1.setText(_translate("MainWindow", "浏览课程"))
        self.label_13.setText(_translate("MainWindow", "输入课程号："))
        self.c_bt4.setText(_translate("MainWindow", "更改信息"))
        self.c_bt5.setText(_translate("MainWindow", "撤销更改"))
        self.c_bt6.setText(_translate("MainWindow", "查询课程"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "课程管理"))
        self.x_bt2.setText(_translate("MainWindow", "添加选课"))
        self.x_bt1.setText(_translate("MainWindow", "浏览选课情况"))
        self.x_bt4.setText(_translate("MainWindow", "查询"))
        self.sum3.setPlaceholderText(_translate("MainWindow", "总数"))
        self.x_bt3.setText(_translate("MainWindow", "删除已选课程"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "学号"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "课程号"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "教工号"))
        self.comboBox_3.setItemText(4, _translate("MainWindow", "成绩合格"))
        self.comboBox_3.setItemText(5, _translate("MainWindow", "成绩不合格"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "选课管理"))
        self.label_3.setText(_translate("MainWindow", "肇庆学院"))
        self.label_4.setText(_translate("MainWindow", "ZHAOQING UNIVERSITY"))
        self.label_5.setText(_translate("MainWindow", "管理员界面"))


if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    myshow = main_function()
    myshow.setupUi(MainWindow)

    MainWindow.show()  # 窗口全屏
    # 连接数据库
    db = QSqlDatabase.addDatabase("QODBC")
    db.setDatabaseName("Driver={Sql Server};Server=localhost;Database=Course_Management;Uid=sa;Pwd=ROOT")
    db.open()
    query = QSqlQuery()
    sys.exit(app.exec_())
