# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'student.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication,QMainWindow,QDialog
from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import Qt, QEvent, QRegExp, QObject
from PyQt5.QtGui import  QRegExpValidator
from PyQt5.QtSql import QSqlQuery,QSqlDatabase,QSqlTableModel,QSqlRelation,QSqlRelationalDelegate, QSqlRelationalTableModel
from PyQt5.QtWidgets import QMainWindow,QDialog, QApplication, QLineEdit, QLabel, QPushButton, QHBoxLayout, QVBoxLayout, QMessageBox
from PyQt5.QtGui import QKeyEvent, QKeySequence, QRegExpValidator
from PyQt5.QtCore import pyqtSlot,pyqtSignal
import q11
class student(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1500, 750)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 60, 151, 16))
        font = QtGui.QFont()
        font.setFamily("Lucida Bright")
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 3, 3);")
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(150, 10, 151, 41))
        font = QtGui.QFont()
        font.setFamily("华文隶书")
        font.setPointSize(26)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 0, 0);")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(60, 10, 71, 71))
        self.label.setStyleSheet("border-image: url(:/image/图片/t16.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 20, 61, 20))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.xiu_mima = QtWidgets.QPushButton(self.centralwidget)
        self.xiu_mima.setGeometry(QtCore.QRect(310, 50, 75, 23))
        self.xiu_mima.setStyleSheet("")
        self.xiu_mima.setObjectName("xiu_mima")
        self.zhuxiao = QtWidgets.QPushButton(self.centralwidget)
        self.zhuxiao.setGeometry(QtCore.QRect(380, 50, 75, 23))
        self.zhuxiao.setObjectName("zhuxiao")
        self.idname = QtWidgets.QLabel(self.centralwidget)
        self.idname.setGeometry(QtCore.QRect(320, 20, 61, 16))
        self.idname.setText("")
        self.idname.setObjectName("idname")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(50, 90, 1311, 611))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 51, 16))
        self.label_5.setObjectName("label_5")
        self.id = QtWidgets.QLineEdit(self.tab)
        self.id.setGeometry(QtCore.QRect(300, 10, 111, 21))
        self.id.setObjectName("id")
        self.bt1 = QtWidgets.QPushButton(self.tab)
        self.bt1.setGeometry(QtCore.QRect(440, 10, 51, 23))
        self.bt1.setObjectName("bt1")
        self.table1 = QtWidgets.QTableWidget(self.tab)
        self.table1.setGeometry(QtCore.QRect(90, 40, 1151, 541))
        self.table1.setObjectName("table1")
        self.table1.setColumnCount(0)
        self.table1.setRowCount(0)
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(91, 11, 81, 20))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.setItemText(0, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab)
        self.comboBox_2.setGeometry(QtCore.QRect(198, 11, 81, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.setItemText(0, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_8 = QtWidgets.QLabel(self.tab_4)
        self.label_8.setGeometry(QtCore.QRect(20, 10, 54, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.comboBox_4.setGeometry(QtCore.QRect(88, 10, 81, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.setItemText(0, "")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.table2 = QtWidgets.QTableWidget(self.tab_4)
        self.table2.setGeometry(QtCore.QRect(90, 40, 1151, 531))
        self.table2.setObjectName("table2")
        self.table2.setColumnCount(0)
        self.table2.setRowCount(0)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        self.label_6.setGeometry(QtCore.QRect(43, 10, 31, 21))
        self.label_6.setObjectName("label_6")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_3.setGeometry(QtCore.QRect(90, 12, 91, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.table3 = QtWidgets.QTableWidget(self.tab_3)
        self.table3.setGeometry(QtCore.QRect(90, 40, 1201, 541))
        self.table3.setObjectName("table3")
        self.table3.setColumnCount(0)
        self.table3.setRowCount(0)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.bt2 = QtWidgets.QPushButton(self.tab_2)
        self.bt2.setGeometry(QtCore.QRect(40, 10, 75, 23))
        self.bt2.setObjectName("bt2")
        self.table4 = QtWidgets.QTableWidget(self.tab_2)
        self.table4.setGeometry(QtCore.QRect(40, 40, 1241, 541))
        self.table4.setObjectName("table4")
        self.table4.setColumnCount(0)
        self.table4.setRowCount(0)
        self.tabWidget.addTab(self.tab_2, "")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(730, 10, 771, 81))
        self.label_7.setStyleSheet("border-image: url(:/image/图片/t6.jpg);")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1500, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)




        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_4.setText(_translate("MainWindow", "ZHAOQING UNIVERSITY"))
        self.label_3.setText(_translate("MainWindow", "肇庆学院"))
        self.xiu_mima.setText(_translate("MainWindow", "修改密码"))
        self.zhuxiao.setText(_translate("MainWindow", "注销"))
        self.label_5.setText(_translate("MainWindow", "搜索范围"))
        self.bt1.setText(_translate("MainWindow", "查询"))
        self.comboBox.setItemText(1, _translate("MainWindow", "课表查询"))
        self.comboBox.setItemText(2, _translate("MainWindow", "教师"))
        self.comboBox.setItemText(3, _translate("MainWindow", "院系"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "查询"))
        self.label_8.setText(_translate("MainWindow", "浏览选择"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "学生"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "教师"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "院系"))
        self.comboBox_4.setItemText(4, _translate("MainWindow", "课程"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "浏览"))
        self.label_6.setText(_translate("MainWindow", "选择"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "已修课程"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "已选课程"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "学生课程浏览"))
        self.bt2.setText(_translate("MainWindow", "个人选课"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "选课报名"))



if __name__ == '__main__':
    app = QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    myshow = student()
    myshow.setupUi(MainWindow)
    MainWindow.show()  # 窗口全屏
    sys.exit(app.exec_())

